services:

  url-app:
    image: syedaftab04/project05-url-shortener:latest 
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - url-app
    networks:
      - backend

  redis:
    image: redis:7-alpine
    networks:
      - backend

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d urlshortener"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  watchtower:
    image: containrrr/watchtower:1.5.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_API_VERSION: "1.54"
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_NOTIFICATION_URL}
    restart: always
    networks:
      - backend

networks:
  backend:

volumes:
  postgres-data:
